name: Publish snapshot

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: macos-latest
    env:
      PUBLISH_RELEASE: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: checkout
        uses: actions/checkout@v2
      - name: publish
        run: ./gradlew publish
